version: '3.8'
services:
  vocpi:
    build: .
    image: vocpi:latest
    container_name: vocpi_app
    # network_mode: "service:otel-sidecar"
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - ./app:/app
    working_dir: /app
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 8000
      --reload

  valkey:
    image: valkey/valkey:latest
    container_name: valkey
    ports:
      - "6379:6379"
    command: ["valkey-server", "--save", "", "--appendonly", "no"]

  otel-sidecar:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command:
      - '--config=/etc/otel-collector-config.yaml'
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - '4317:4317' # OTLP gRPC receiver
      - '55681:55681' # Prometheus receiver