version: '3.8'
services:
  lan_app:
    build: .
    image: lan_app:latest
    container_name: lan_app
    # network_mode: "service:otel-sidecar"
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - ./docs:/app/docs:ro
  otel-sidecar:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command:
      - '--config=/etc/otel-collector-config.yaml'
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - '4317:4317' # OTLP gRPC receiver
      - '55681:55681' # Prometheus receiver